---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: springio/github-changelog-generator
    tag: '0.0.8'
    username: ((docker-hub-username))
    password: ((docker-hub-password))
inputs:
- name: git-repo
- name: artifactory-repo
outputs:
- name: generated-changelog
run:
  path: git-repo/ci/scripts/generate-changelog.sh
