---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: springio/concourse-release-scripts
    tag: '0.3.4'
    username: ((docker-hub-username))
    password: ((docker-hub-password))
inputs:
- name: git-repo
- name: artifactory-repo
run:
  path: git-repo/ci/scripts/promote.sh
